### ISSUE TITLE
S3 Target - support profile based authentication

### ISSUE THREAD

**Issue by asksmruti** [transferwise/pipelinewise-target-s3-csv#15]
Dear Team,

Is it possible to implement AWS profile or assume role based authentication for S3 target.
Right now, it seems that it picks hard coded credentials.

aws_access_key_id: "<ACCESS_KEY>" # S3 - Plain string or vault encrypted
aws_secret_access_key: "<SECRET_ACCESS_KEY>" # S3 - Plain string or vault encrypted

**Comment by asksmruti** [comment]
Unfortunately, I am unable to raise PR. this is the piece of code to enable aws_profile based authentication. At this point, I wanted to add to fix this issue. Could someone please have a look - 

`def setup_aws_client(config):
    LOGGER.info("Attempting to create AWS session")
    if config["aws_profile"]:
        boto3.setup_default_session(profile_name=config["aws_profile"])
    else:
        boto3.setup_default_session(aws_access_key_id=config['aws_access_key_id'],
                                    aws_secret_access_key=config['aws_secret_access_key'])`

**Comment by koszti** [comment]
hey @asksmruti , 

this has been addressed by #22 and releases to pypi as 1.3.0 of this connector.

It will be linked soon is in the main PPW by https://github.com/transferwise/pipelinewise/pull/492
