### ISSUE TITLE
Error on building this target

### ISSUE THREAD

**Issue by jmriego** [transferwise/pipelinewise-target-s3-csv#16]
Hi! when building this target during the `install.sh` of PipelineWise it's failing for me with this error:
`ERROR: pipelinewise-singer-python 1.1.3 has requirement jsonschema==3.2.0, but you'll have jsonschema 2.6.0 which is incompatible.`

I think removing the dependency from this repo should be enough as it would download the 3.2.0 version anyway because of `singer-python` similar to what happened in the `tap-mysql`

Thanks!

**Comment by koszti** [comment]
thanks, this has now been fixed by 76813984f0eac27855566c91ed24a8a8040e8d3e, released as 1.2.1 and piplinewise master build is working again.
