### ISSUE TITLE
Support for gzipped CSVs (csv.gz)?

### ISSUE THREAD

**Issue by aaronsteers** [transferwise/pipelinewise-target-s3-csv#4]
Hello! I'm excited to use this target for data pipelines but wanted to ask if there's any current plan to add support for gzipped CSV format. Because csv.gz format can be read/write/scanned serially, and because of the reduced network IO involved in pulling from the compressed sources, most big data applications (including Pandas and Spark) have native support for CSV.GZ.

Would be awesome if gzip support could also be added here in this target, to allow these tools more performance reads to CSV data files in S3.

**Comment by koszti** [comment]
hey @aaronsteers sorry for the late reply.

gzip and bzip2 is already supported in [pipelinewise-target-redshift](https://github.com/transferwise/pipelinewise-target-redshift/commit/8451066b7f9451ca7892e628552b73ae179c1f70) and we would like to add it to pipelinewise-target-snowflake in the near future. Adding the same functionality to this target-s3-csv would be awesome, but it's currently not in our quarterly roadmap. :(

But the code change is relatively small and we'd like to behave as the same as the target-redshift by adding the `compression` optional paramter to `config.json`. If you're happy to contribute please have a look how it's implemented in pipelinewise-target-redshift , PR and we can review much earlier. It's a relatively small code change.

**Comment by aaronsteers** [comment]
Thanks, @koszti - this is helpful info. I don't know if/when I'll be able to prioritize the work but certainly I'm interested. If anyone else gets bandwidth to pick it up, would be great to see it added. It's very helpful to have the links to related projects and I'm glad to hear it fits with the general roadmap/direction. 👍

**Comment by aaronsteers** [comment]
I've created a related Issue on the pipelinewise `target-s3-csv` repo here: https://github.com/transferwise/pipelinewise-target-s3-csv/issues/5

I imagine the code to accomplish both is very similar, and would be great if the settings/config needed on both side are similar or identical.

**Comment by aaronsteers** [comment]
Resolved by #7. 

Paired with #6, this would allow for both compression and custom encryption, which open up some additional use cases on my side for this target.

**Comment by koszti** [comment]
Thank you, #7 got merged but #6 is having some conflicts. Can you please take a look, fix it and I'm ok to merge both. 🙇

**Comment by koszti** [comment]
Solved by https://github.com/transferwise/pipelinewise-target-s3-csv/pull/7
