### ISSUE TITLE
Runtime exception

### ISSUE THREAD

**Issue by anticse** [transferwise/pipelinewise-target-s3-csv#43]
I'm getting a runtime exception when i'm using tap-Bigquery target-s3 
```
raise Exception("Config is missing required keys: {}".format(missing_keys))
Exception: Config is missing required keys: ['summoner_name', 'region', 'queue', 'season']
```
This is the command i'm trying to run
```
~/Documents/bq_s3/BQ/bin/tap-bigquery -c ~/Documents/bq_s3/BQ/bin/tap_config.json -d > catalog.json | ~/Documents/bq_s3/pipline_target_s3/venv/bin/target-s3 -c ~/Documents/bq_s3/pipline_target_s3/venv/bin/config.json
```
I have passed s3_bucket name, aws key id, aws,secret key in the target3 config.json

**Comment by Samira-El** [comment]
Hey,

The error you've shared doesn't seem to be coming from this target, there is no `raise Exception("Config is missing required keys: {}".format(missing_keys))` line in the code base, also, those keys are not required in target_s3_csv. Perhaps the issue is coming from tap-bigquery.

**Comment by anticse** [comment]
Ok this was fixed by passing some default values for  `missing_keys` .
btw, does this `target` only support taps that are listed in `https://transferwise.github.io/pipelinewise/` ?

**Comment by Samira-El** [comment]
> btw, does this target only support taps that are listed in https://transferwise.github.io/pipelinewise/ ?

If you run it within PipelineWise then yes, otherwise, no.
