### ISSUE TITLE
Support for encryption (KMS and/or client-provided key)

### ISSUE THREAD

**Issue by aaronsteers** [transferwise/pipelinewise-target-s3-csv#5]
Related to another PR on `tap-s3-csv` [here](https://github.com/singer-io/tap-s3-csv/issues/11), it would be awesome to include support for S3 encryption. The easiest is probably to support KMS encryption, since that just requires the name of a valid KMS key and I think we can even default to the default KMS key if the name is not provided.

Another nice capability which should at least be considered when creating the settings spec, would be how to support client-provided keys, either those hosted/registered in AWS (server-side) or those that might be within a local file/property (client-side).

Related ref: https://www.justdocloud.com/2018/09/21/upload-download-s3-using-aws-kms-python/

**Comment by aaronsteers** [comment]
The linked PR is ready for review. 👍

**Comment by koszti** [comment]
Solved by https://github.com/transferwise/pipelinewise-target-s3-csv/pull/7
