### ISSUE TITLE
Target reorders columns/properties in output CSV (forces alphabetical sort)

### ISSUE THREAD

**Issue by lpillmann** [transferwise/pipelinewise-target-s3-csv#73]
**Describe the bug**
Target is sorting the columns alphabetically in output CSVs. The correct approach would be to keep the same order as seen in the schema definition (passed as schema message). At least we should provide the option for the user to choose.

**To Reproduce**
1. Prepare a tap with any schema in which columns are not ordered alphabetically
2. Run tap & target
3. Inspect output CSV and see the columns reordered alphabetically

**Expected behavior**
The order of the columns (a.k.a. properties) should be kept the same as in the schema definition.

**Screenshots**
n/a

**Your environment**
 - Version of target: 1.4.0 (2020-09-09)
 - Version of python 3.6, 3.8

**Additional context**
My use case was to load CSVs to S3 and then copy to Redshift. In order for Redshift to copy the data, one must create a table first, e.g. `CREATE TABLE mytable (id text, name text, age integer)`. So it expects the CSV columns to be `id,name,age`. However, because the target is sorting the output columns, it becomes `age,id,name` which breaks the pipeline.

I've already forked the repo and [fixed the issue](https://github.com/lpillmann/pipelinewise-target-s3-csv/commit/6105a4552f7bf97364556e671b499a4d85fbe443) to my use case. I'm reporting here 'cause I'm confident this might be an issue for other folks too. I'd be happy to do a PR for that, if you share the same understanding.

**Comment by Samira-El** [comment]
Hey, the schema definition is a json and order in JSON objects is not guaranteed, nor does it nor should it matter.

While I do agree that I don't see a point in sorting the properties, I'm afraid you might be relying too much on order.
Perhaps, if your use case is to load to Redshift, then perhaps, use target redshift instead which will take care of a lot of these details for you.

**Comment by lpillmann** [comment]
Hi Samira, thanks for reminding me of that.

I've been relying on the order and it has worked so far - but, indeed, it could be risky to assume it would always be the case for all taps.

So it might actually make sense to sort the columns as it is, so we avoid any unintended swaps. Then in my use case I'd need to change the `create table` statements to have the columns ordered. It messes with the usability of the tables, but I could fix it in downstream Redshift models.
